SUCRMS/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SUCRMS.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please provide Department Name")]
        [DisplayName("Department Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please provide Department Code")]
        [StringLength(7, MinimumLength = 2)]
        [DisplayName("Department Code")]
        public string Code { get; set; }
        public int Serials { get; set; }
    }
}

SUCRMS/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SUCRMS.BLL;
using SUCRMS.Models;

namespace SUCRMS.Controllers
{
    public class DepartmentController : Controller
    {
        //
        // GET: /Department/
        DepartmentManager departmentManager = new DepartmentManager();
        public ActionResult Save()
        {
            
            return View();

        }
        [HttpPost]
        public ActionResult Save(Department department)
        {
            try
            {

                int rowsAffected = departmentManager.Save(department);
                if (rowsAffected > 0)
                {
                    ViewBag.Message = "Saved";
                }
                else
                {
                    ViewBag.Message = "Fail";
                }
            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.Message;
            }
            return View();

        }
        public ActionResult Index()
        {
            var departmentlist = departmentManager.GetAllDepartment();
            ViewBag.Department = departmentlist;
            return View();
        }

        
    }
}

SUCRMS/Views/Department/Index.cshtml
@using SUCRMS.Models
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Department> departments = ViewBag.Department;
}

<section class="content-header">
    <h1>
        Department
        <small>View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Department</a></li>
        <li class="active">View</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary col-sm-12">
                <div class="box-header with-border">
                    <div class="col-sm-12">
                        @Html.ActionLink("Add New", "Save", "Department", new { @class = "btn btn-primary btn-sm" })
                    </div>
                    @*<h3 class="box-title" style="">All Department</h3>*@
                </div>
                <div class="box-body">
                    <table border="1" class="table table-bordered table-condensed" id="view">
                        <thead>
                        <tr>
                            <th>Code</th>
                            <th>Name</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (departments != null)
                        {

                            foreach (Department department in departments)
                            {
                                <tr>

                                    <td>@department.Code</td>
                                    <td>@department.Name</td>
                                </tr>

                            }
                        }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</section>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/DataTables/responsive.bootstrap.min.js"></script>
<script>
    $(document).ready(function () {

        $('#view').DataTable();
    });
</script>

SUCRMS/Views/Department/Save.cshtml
@using SUCRMS.Models
@model SUCRMS.Models.Department
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Department 
        <small>Save</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Department</a></li>
        <li class="active">Save</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary col-sm-12">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add Department</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form id="department" method="POST">

                        @if (ViewBag.Message != null)
                        {
                            if (ViewBag.Message == "Saved")
                            {
                                <div class="col-sm-12"></div>
                                <div class="alert alert-success" id="success-alert">
                                    <button type="button" class="close" data-dismiss="alert">x</button>
                                    <strong>Successfully saved! </strong>
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12">
                                    <div class="alert alert-error" id="success-alert">
                                        <button type="button" class="close" data-dismiss="alert">x</button>
                                        <strong>Faild save! </strong>
                                        <p>@ViewBag.Message</p>
                                    </div>
                                </div>
                            }

                        }
                        @Html.ValidationSummary(true)
                        <div class="box-body">
                            <div class="form-group">

                                <label for="Code">Code</label>
                                <input type="text" class="form-control input-sm" id="Code" name="Code" placeholder="Code">
                                @Html.ValidationMessageFor(m => m.Code)
                            </div>

                            <div class="form-group">

                                <label for="Name">Name</label>
                                <input type="text" class="form-control input-sm" id="Name" name="Name" placeholder="Name">
                                @Html.ValidationMessageFor(m => m.Name)
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                                @Html.ActionLink("Back", "Index", "Department", new { @class = "btn btn-danger btn-sm" })
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>


<script>

    $(document).ready(function () {
        //alert('sdfds');
        $("#department").validate({
            rules: {
                Name: "required",
                Code: {
                    required: true,
                    minlength: 2,
                    maxlength: 7
                }
            },
            messages: {
                Name: "Please Provide Department Name",

                Code: {
                    required: "Please enter a value between 2 to 7 characters!"
                }
            }
        });
    });
</script>