SUCRMS/Models/CourseAssignToTeacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SUCRMS.Models
{
    public class CourseAssignToTeacher
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int TeacherId { get; set; }
        public int CourseId { get; set; }
        public int Status { get; set; }
        public double CourseCredit { get; set; }
    }
}

SUCRMS/Controllers/CourseAssignToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SUCRMS.BLL;
using SUCRMS.Models;
using WebGrease.Css.Ast.Selectors;

namespace SUCRMS.Controllers
{
    public class CourseAssignToTeacherController : Controller
    {
        //
        // GET: /CourseAssignToTeacher/
        CourseAssignToTeacherManager courseAssignToTeacherManager = new CourseAssignToTeacherManager();
        public ActionResult Index()
        {
            ViewBag.Departments = GetAllDepartments();
            return View();
        }

        [HttpPost]
        public ActionResult Index(CourseAssignToTeacher courseAssignToTeacher)
        {
            try
            {
                int rowsAffected = courseAssignToTeacherManager.Save(courseAssignToTeacher);
                int updated = courseAssignToTeacherManager.UpdateTeacherRemainCredit(courseAssignToTeacher);
                if (rowsAffected > 0 && updated > 0)
                {
                    ViewBag.Message = "Saved";
                }
                else
                {
                    ViewBag.Message = "Fail";
                }
            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.Message;
            }
            ViewBag.Departments = GetAllDepartments();
            return View();

        }

        DepartmentManager departmentManager = new DepartmentManager();
        private List<Department> GetAllDepartments()
        {
            return departmentManager.GetAllDepartment();
        }

        TeacherManager teacherManager = new TeacherManager();
        private List<Teacher> GetAllTeacher()
        {
            return teacherManager.GetAllTeacher();
        }

        CourseManager courseManager = new CourseManager();
        private List<Course> GetAllCourse()
        {
            return courseManager.GetAllCourse();
        }

        public JsonResult GetTeacherByDepartmentId(int departmentId)
        {
            List<Teacher> teacherList = null;
            if (departmentId > 0)
            {
                var teachers = GetAllTeacher();
                teacherList = teachers.Where(a => a.DepartmentId == departmentId).ToList();
            }
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCourseByDepartmentId(int departmentId)
        {
            List<Course> courselList = null;
            if (departmentId > 0)
            {
                var courses = GetAllCourse();
                courselList = courses.Where(a => a.DepartmentId == departmentId).ToList();
            }
            return Json(courselList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTeacherInfoByTeacherId(int teacherId)
        {
            List<Teacher> teacherList = null;
            if (teacherId > 0)
            {
                var teachers = GetAllTeacher();
                teacherList = teachers.Where(a => a.Id == teacherId).ToList();
            }
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCourseInfoByCourseId(int courseId)
        {
            List<Course> courseList = null;
            if (courseId > 0)
            {
                var courses = GetAllCourse();
                courseList = courses.Where(a => a.Id == courseId).ToList();
            }
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UnallocationCourseAssignToTeacher()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnallocationCourseAssignToTeacher(CourseAssignToTeacher courseAssignToTeacher)
        {
            int rowsAffected = courseAssignToTeacherManager.UnallocationCourseAssignToTeacher(courseAssignToTeacher);
            if (rowsAffected > 0)
            {
                ViewBag.Message = "Unassign Teacher Successfully";
            }
            else
            {
                ViewBag.Message = "Unassign failed";
            }
            return View();
        }
    }
}

SUCRMS/Views/CourseAssignToTeacher/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Course Assign to Teacher
        <small>Save</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Course Assign to Teacher</a></li>
        <li class="active">Save</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary col-sm-12">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="box-header with-border">
                        <h3 class="box-title">Assign Course</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form id="CourseAssighToTeacher" method="POST">

                        @if (ViewBag.Message != null)
                        {
                            if (ViewBag.Message == "Saved")
                            {
                                <div class="col-sm-12"></div>
                                <div class="alert alert-success" id="success-alert">
                                    <button type="button" class="close" data-dismiss="alert">x</button>
                                    <strong>Successfully saved! </strong>
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12">
                                    <div class="alert alert-error" id="success-alert">
                                        <button type="button" class="close" data-dismiss="alert">x</button>
                                        <strong>Faild save! </strong>
                                        <p>@ViewBag.Message</p>
                                    </div>
                                </div>
                            }

                        }
                        @Html.ValidationSummary(true)
                        <div class="box-body">
                            <div class="form-group">

                                <label for="DepartmentId">Department</label>
                                <select class="form-control input-sm" name="DepartmentId" id="DepartmentId">
                                    <option value="">Select a Department</option>
                                    @foreach (var department in ViewBag.Departments)
                                    {
                                        <option value="@department.Id">@department.Name</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="TeacherId">Teacher</label>
                                <select class="form-control input-sm" name="TeacherId" id="TeacherId">
                                    <option value="">Select a Teacher</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="CreditTobeTaken">Credit to be Taken</label>
                                <input class="form-control input-sm" name="CreditTobeTaken" id="CreditTobeTaken" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="RemainingCredit">Remaining Credit</label>
                                <input class="form-control input-sm" name="RemainingCredit" id="RemainingCredit" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="CourseId">Course Code</label>
                                <select class="form-control input-sm" name="CourseId" id="CourseId">
                                    <option value="">Select a Course Code</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="CourseName">Name</label>
                                <input class="form-control input-sm" name="CourseName" id="CourseName" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="CourseCredit">Credit</label>
                                <input class="form-control input-sm" name="CourseCredit" id="CourseCredit" readonly="" />
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {

        $("#DepartmentId").change(function () {
            var deptId = $("#DepartmentId").val();
            $("#TeacherId").empty();
            var json = {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacherByDepartmentId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    //alert(data);
                    $("#TeacherId").append("<option value=''>Select a Teacher</option>");

                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#TeacherId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                    });
                    getCourse();
                }
            });
            //getCourse();
        });

        function getCourse() {
            //alert("in");
            var deptId = $("#DepartmentId").val();
            $("#CourseId").empty();
            var json = {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseByDepartmentId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    //alert(data);
                    $("#CourseId").append("<option value=''>Select a Course Code</option>");

                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');
                    });
                }
            });
        }

        $("#TeacherId").change(function () {
            //alert("in teacher");
            var teacherId = $("#TeacherId").val();
            var json = {
                teacherId: teacherId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacherInfoByTeacherId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    //alert(data);
                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#CreditTobeTaken").val(value.CreditTobeTaken);
                        $("#RemainingCredit").val(value.RemainingCredit);
                    });
                }
            });
        });

        $("#CourseId").change(function () {
            //alert("in course");
            var courseId = $("#CourseId").val();
            var json = {
                courseId: courseId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseInfoByCourseId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    //alert(data);
                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#CourseName").val(value.Name);
                        $("#CourseCredit").val(value.Credit);
                    });
                }
            });
        });

        // Validation

        $("#CourseAssighToTeacher").validate({
            rules: {
                DepartmentId: "required",
                TeacherId: "required",
                CourseId: "required"
            },
            messages: {
                DepartmentId: "Please Select a Department",
                TeacherId: "Please Select a Teacher",
                CourseId: "Please Select a Course"
            }
        });

        $(function () {
            $("#CourseAssighToTeacher").submit(function (e) {
                var CourseCredit = $("#CourseCredit").val();
                var RemainingCredit = $("#RemainingCredit").val();

                if (CourseCredit > RemainingCredit) {
                    var r = confirm("Course Credit is exceeding the Remaining Credit. Are you sure you want to proceed?");
                    if (r == true) {
                       
                    } else {
                        e.preventDefault();
                    }
                }

            });
        });

    });
</script>

SUCRMS/Views/CourseAssignToTeacher/UnallocationCourseAssignToTeacher.cshtml
@{
    ViewBag.Title = "UnallocationCourseAssignToTeacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Unassign All Courses
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Unassign All Courses</a></li>

    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary col-sm-12">
                <div class="col-sm-8 col-sm-offset-2">

                    <!-- /.box-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("UnallocationCourseAssignToTeacher", "CourseAssignToTeacher", FormMethod.Post, new { @class = "form-horizontal", @id = "unassign" }))
                    {

                        if (ViewBag.Message != null)
                        {
                            if (ViewBag.Message == "Unassign Teacher Successfully")
                            {
                                <div class="col-sm-12"></div>
                                <div class="alert alert-success" id="success-alert">
                                    <button type="button" class="close" data-dismiss="alert">x</button>
                                    <strong>Successfully! </strong>
                                    <p>All Courses has been Unassigned</p>
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12">
                                    <div class="alert alert-error" id="success-alert">
                                        <button type="button" class="close" data-dismiss="alert">x</button>
                                        <strong>Faild! </strong>
                                        <p>@ViewBag.Message</p>
                                    </div>
                                </div>
                            }

                        }
                        @Html.ValidationSummary(true)
                        <div class="box-body">
                            <div class="col-sm-12 text-center" style="padding: 20px">
                                <button type="submit" class="btn btn-danger btn-Lg" onclick="Submit();">Unassign All Courses </button>
                            </div>

                            <div class="box-footer">


                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</section>

<script type="text/javascript">
    $(document).ready(function () {

        $(function () {
            $("#unassign").submit(function (e) {

                var r = confirm("Are you sure that you want to Unassign all Courses?");
                if (r != true) {
                    e.preventDefault();
                }
            });
        });

    });
</script>