SUCRMS/Models/SaveStudentResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace SUCRMS.Models
{
    public class SaveStudentResult
    {
        public int ResultId { get; set; }
        public int CourseId { get; set; }
        [DisplayName("Grade")]
        public int GradeId { get; set; }
        [DisplayName("Student Reg. No")]
        public int StudentId { get; set; }

    }
}

SUCRMS/Controllers/SaveStudentResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SUCRMS.BLL;
using SUCRMS.Models;

namespace SUCRMS.Controllers
{
    public class SaveStudentResultController : Controller
    {
        //
        // GET: /SaveStudentResult/
        SaveStudentResultManager saveStudentResultManager = new SaveStudentResultManager();
        //
        // GET: /EnrollCourse/
        public ActionResult Save()
        {
            ViewBag.Student = GetAllstudents();
            
            ViewBag.Grade = GetAllGrades();
            return View();
        }
        [HttpPost]
     
        public ActionResult Save(SaveStudentResult saveStudentResult)
        {
            try
            {

                int rowsAffected = saveStudentResultManager.Save(saveStudentResult);
                if (rowsAffected > 0)
                {
                    ViewBag.Message = "Saved";
                }
                else
                {
                    ViewBag.Message = "Fail";
                }
            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.Message;
            }
            ViewBag.Student = GetAllstudents();
            
            ViewBag.Grade = GetAllGrades();
            return View();
        }
        StudentManager studentManager = new StudentManager();
        private List<Student> GetAllstudents()
        {
            var studentList = studentManager.GetAllStudent();
            return studentList;
        }

        CourseManager courseManager = new CourseManager();
        private List<Course> GetAllCourses()
        {
            var courseList = courseManager.GetAllCourse();
            return courseList;
        }

        public ActionResult GetCourseByDepartmentId(int departmentId)
        {
            List<Course> courselList = null;
            if (departmentId > 0)
            {
                var courses = GetAllCourses();
                courselList = courses.Where(a => a.DepartmentId == departmentId).ToList();
            }
            return Json(courselList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetNameByRegNo(int StudenId)
        {
            List<Student> StudentList = null;
            if (StudenId > 0)
            {
                var students = GetAllstudents();
                StudentList = students.Where(a => a.Id == StudenId).ToList();
            }
            return Json(StudentList, JsonRequestBehavior.AllowGet);
        }

        DepartmentManager departmentManager = new DepartmentManager();
        private List<Department> GetAllDepartments()
        {
            var departmentlist = departmentManager.GetAllDepartment();
            return departmentlist;
        }

        public JsonResult GetdepartmentByRegNo(int departmentId)
        {
            List<Department> DepartmentList = null;
            if (departmentId > 0)
            {
                var department = GetAllDepartments();
                DepartmentList = department.Where(a => a.Id == departmentId).ToList();
            }
            return Json(DepartmentList, JsonRequestBehavior.AllowGet);
        }

        GradeManager gradeManager = new GradeManager();
        private List<Grade> GetAllGrades()
        {
            var GradeList = gradeManager.GetAllGrade();
            return GradeList;
        }
	}
}

SUCRMS/Views/SaveStudentResult/Save.cshtml
@using SUCRMS.Models
@model SUCRMS.Models.SaveStudentResult
@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Student Result
        <small>Save</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Save Student Result</a></li>
        <li class="active">Save</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary col-sm-12">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="box-header with-border">
                        <h3 class="box-title">Save Student Result</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Save", "SaveStudentResult", FormMethod.Post, new { @class = "form-horizontal", @id = "SaveStudentResult" }))
                    {


                        if (ViewBag.Message != null)
                        {
                            if (ViewBag.Message == "Saved")
                            {
                                <div class="col-sm-12"></div>
                                <div class="alert alert-success" id="success-alert">
                                    <button type="button" class="close" data-dismiss="alert">x</button>
                                    <strong>Successfully saved! </strong>
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12">
                                    <div class="alert alert-error" id="success-alert">
                                        <button type="button" class="close" data-dismiss="alert">x</button>
                                        <strong>Save Faild! </strong>
                                        <p>@ViewBag.Message</p>
                                    </div>
                                </div>
                            }

                        }
                        @Html.ValidationSummary(true)
                        <div class="box-body">
                            <div class="form-group">
                                @Html.LabelFor(a => a.StudentId)
                                @Html.DropDownListFor(a => a.StudentId, new SelectList(ViewBag.Student, "Id", "RegistrationId"), "Select a Reg No", new { @class = "form-control input-sm" })
                                @Html.ValidationMessageFor(m => m.StudentId)
                            </div>

                            <div class="form-group">
                                <label for="Name">Name</label>
                                <input class="form-control input-sm" name="Name" id="Name" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="Email">Email</label>
                                <input class="form-control input-sm" name="Email" id="Email" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="dptid">Department</label>
                                <input class="form-control input-sm" name="Department" id="dptid" readonly="" />
                            </div>
                            <div class="form-group">
                                <label for="CourseId">Course Code</label>
                                <select class="form-control input-sm" name="CourseId" id="CourseId">
                                    <option value="">Select a Course Code</option>
                                </select>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(a => a.GradeId)
                                @Html.DropDownListFor(a => a.GradeId, new SelectList(ViewBag.Grade, "Id", "Name"), "Select a Grade", new { @class = "form-control input-sm" })
                                @Html.ValidationMessageFor(m => m.GradeId)
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        var departmentids = null;
        var studentnumber = null;
        $("#StudentId").change(function () {
            var StudenId = $("#StudentId").val();
            $("#Name").val("");
            $("#Email").val("");
            $("#dptid").val("");
            $("#CourseId").empty();
            var json = {
                StudenId: StudenId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetNameByRegNo", "SaveStudentResult")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    //alert(data);
                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#Name").val(value.Name);
                        $("#Email").val(value.Email);
                        departmentids = value.DepartmentId;
                        studentnumber = value.RegistrationId;
                        //alert(departmentids);
                    });
                    getdepartment();
                }
            });
            //getCourse();
        });

        function getdepartment() {
           // alert("in");
            var deptId = departmentids;

            $("#dptid").val("");
            var json = {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetdepartmentByRegNo", "SaveStudentResult")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data1) {
                    $.each(data1, function (key, value) {
                        if (value == "") {

                        }else{
                            $("#dptid").val(value.Code);
                            }
                    });
                    getCourse();
                }

            });
            
        }

        function getCourse() {
            //alert("in");

            var deptId1 = departmentids;
            //alert("Your Selected Registration Number: " + studentnumber);

            var json = {
                departmentId: deptId1
            };

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseByDepartmentId", "SaveStudentResult")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {

                    $("#CourseId").append("<option value=''>Select a Course Code</option>");

                    $.each(data, function (key, value) {
                        if (value == "") {

                        }else{
                        //alert(key);
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');
                        }
                    });
                }
            });
        }

        // Validation

        $("#EnrollCourse").validate({
            rules: {
                DepartmentId: "required",
                TeacherId: "required",
                CourseId: "required"
            },
            messages: {
                DepartmentId: "Please Select a Department",
                TeacherId: "Please Select a Teacher",
                CourseId: "Please Select a Course"
            }
        });



    });
</script>